export default {
    ADD_SUBREDDIT: 'ADD_SUBREDDIT',
    REMOVE_SUBREDDIT: 'REMOVE_SUBREDDIT',
    ADD_SUBREDDIT_POSTS: 'ADD_SUBREDDIT_POSTS',
    SET_BACKGROUND_TASK_PROPERTY: 'SET_BACKGROUND_TASK_PROPERTY',
    REPLACE_STATE: 'REPLACE_STATE',
    RESET_STATE: 'RESET_STATE'
};
