export default {
    ADD_SUBREDDIT: 'ADD_SUBREDDIT',
    REMOVE_SUBREDDIT: 'REMOVE_SUBREDDIT',
    ADD_SUBREDDIT_POSTS: 'ADD_SUBREDDIT_POSTS',
    TOGGLE_BACKGROUND_TASK: 'TOGGLE_BACKGROUND_TASK',
    REPLACE_STATE: 'REPLACE_STATE',
    RESET_STATE: 'RESET_STATE'
};
